---
AWSTemplateFormatVersion: '2010-09-09'

Description: "IaC for https://github.com/nicc777/home-tunnel-via-csp"

#######################################################################################################################
###
###     PARAMETERS
###
#######################################################################################################################

Parameters:

  CumulusTunnelBucketNameParam:
    Type: 'String'
    MinLength: 1

  ArtifactBucketNameParam:
    Type: 'String'
    MinLength: 1

  LambdaFunctionCreatedS3KeyParam:
    Type: 'String'
    MinLength: 1
    Default: "handler_s3_object_created.zip"

  LambdaFunctionDeletedS3KeyParam:
    Type: 'String'
    MinLength: 1
    Default: "handler_s3_object_deleted.zip"

  LambdaFunctionExpiredS3KeyParam:
    Type: 'String'
    MinLength: 1
    Default: "handler_s3_object_expired.zip"

  CumulusTunnelCommanderS3KeyParam:
    Type: 'String'
    MinLength: 1
    Default: "handler_cumulus_tunnel_commander.zip"

  CumulusTunnelApiAuthorizerS3KeyParam:
    Type: 'String'
    MinLength: 1
    Default: "handler_cumulus_tunnel_authorizer.zip"

  VpcId1Param:
    Type: 'String'
    MinLength: 1

  VpcCidrParam:
    Type: 'String'
    MinLength: 1

  SubnetId1Param:
    Type: 'String'
    MinLength: 1

  SubnetId2Param:
    Type: 'String'
    MinLength: 1

  SubnetId3Param:
    Type: 'String'
    MinLength: 1

  DebugParam:
    Type: 'String'
    Default: "0"
    Description: "To enable DEBUG logging for AWS Lambda function, set this value to 1"

  CumulusTunnelAmiIdParam:
    Type: 'String'
    MinLength: 1
    Description: "The AMI to use."

  StateFileKeyParam:
    Type: 'String'
    MinLength: 1
    Default: "cumulus-tunnel-state.json"

  DefaultRoute53ZoneIdParam:
    Type: 'String'
    MinLength: 1
    Description: "The default Route 53 Zone ID for DNS records. Will also be used for the management UI record"

  DefaultRoute53DomainParam:
    Type: 'String'
    MinLength: 1
    Description: "The default domain"

  ManagementDomainRecordParam:
    Type: 'String'
    MinLength: 1
    Description: "The default management sub-domain for the management UI"
    Default: "cumulus-tunnel-admin"

  DomainCertificateArnParam:
    Type: 'String'
    MinLength: 1
    Description: "ACM Certificate for the default domain"


#######################################################################################################################
###
###     RESOURCES
###
#######################################################################################################################

Resources:

  ########################################
  ###
  ### SECURITY GROUP (FIREWALL)
  ###
  ########################################

  TunnelInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the EC2 Instance hosting the tunnels
      VpcId: !Ref VpcId1Param
      GroupName: cumulus-tunnel-instance-sg

  TunnelInstanceSgIpv4Port80Ingress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId:
        Fn::GetAtt:
          - TunnelInstanceAlbSecurityGroup
          - GroupId
      GroupId: !GetAtt TunnelInstanceSecurityGroup.GroupId

  TunnelInstanceSgIpv4Port8081Ingress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 8081
      ToPort: 8081
      SourceSecurityGroupId:
        Fn::GetAtt:
          - TunnelInstanceAlbSecurityGroup
          - GroupId
      GroupId: !GetAtt TunnelInstanceSecurityGroup.GroupId

  TunnelInstanceSgIpv4Egress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      CidrIp: 0.0.0.0/0
      GroupId: !GetAtt TunnelInstanceSecurityGroup.GroupId
      IpProtocol: "-1"

  TunnelInstanceSgIpv6Egress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      CidrIpv6: "::/0"
      GroupId: !GetAtt TunnelInstanceSecurityGroup.GroupId
      IpProtocol: "-1"

  ########################################
  ###
  ### SECURITY GROUP (FIREWALL) ALB
  ###
  ########################################

  TunnelInstanceAlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the EC2 Instance hosting the tunnels
      VpcId: !Ref VpcId1Param
      GroupName: cumulus-tunnel-alb-sg

  TunnelInstanceAlbSgIpv4Egress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      CidrIp: 0.0.0.0/0
      GroupId: !GetAtt TunnelInstanceAlbSecurityGroup.GroupId
      IpProtocol: "-1"

  TunnelInstanceAlbSgIpv6Egress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      CidrIpv6: "::/0"
      GroupId: !GetAtt TunnelInstanceAlbSecurityGroup.GroupId
      IpProtocol: "-1"


  ########################################
  ###
  ### EC2 TUNNEL INSTANCE LAUNCH TEMPLATE
  ###
  ########################################

  CumulusTunnelInstanceRole1:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Sid: CumulusTunnelAllowStsAssumeRole
          Effect: 'Allow'
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
      - !ImportValue CumulusTunnelSsmPolicyArn
      Policies:
      - PolicyName: 'Ec2SecretsManager01'
        PolicyDocument:
          Version: '2012-10-17'
          Statement: 
          - Action: 
            - 'secretsmanager:GetSecretValue'
            - 'secretsmanager:DescribeSecret'
            Effect: 'Allow'
            Resource: !ImportValue  CumulusTunnelAuthTokenSecretArn
      - PolicyName: 'ArtifactBucketPolicy01'
        PolicyDocument:
          Version: '2012-10-17'
          Statement: 
          - Action: 
            - 's3:HeadObject'
            - 's3:GetObject'
            - 's3:ListObjectsV2'
            - 's3:CopyObject'
            Effect: 'Allow'
            Resource: 
              Fn::Sub: 
              - 'arn:aws:s3:::${Bucket}/*'
              - Bucket: !Ref ArtifactBucketNameParam
      # TODO Add admin of security groups
      Path: /
      RoleName: !Sub '${AWS::StackName}-CumulusTunnelInstanceRole1'

  CumulusTunnelProfile: 
    Type: 'AWS::IAM::InstanceProfile'
    Properties: 
      Path: '/'
      Roles: 
      - Ref: CumulusTunnelInstanceRole1

  InstanceHostLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    DependsOn: TunnelInstructionQueue
    Properties:
      LaunchTemplateName: !Sub '${AWS::StackName}-LaunchTemplate'
      LaunchTemplateData:
        BlockDeviceMappings:
        - Ebs:
            VolumeSize: 8
            VolumeType: 'gp2'
            DeleteOnTermination: True
            Encrypted: True
          DeviceName: '/dev/sda1'
        ImageId: !Ref CumulusTunnelAmiIdParam
        InstanceType: 't4g.nano'
        IamInstanceProfile: 
          Arn: !GetAtt CumulusTunnelProfile.Arn
        SecurityGroupIds:
        - !Ref TunnelInstanceSecurityGroup
        - !ImportValue CumulusTunnelSsmSecurityGroupId
        MetadataOptions:
          HttpTokens: 'required'
        UserData: 
          Fn::Base64: 
            Fn::Sub:
            - |
              MIME-Version: 1.0
              Content-Type: multipart/mixed; boundary="==BOUNDARY=="

              --==BOUNDARY==
              Content-Type: text/x-shellscript; charset="us-ascii"

              #!/bin/bash

              apt update && apt install -y unzip
              curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install

              echo "SecretArn      : ${SecretArn}"
              echo "ArtifactBucket : ${ArtifactBucket}"

              export HTTP_PW_SECRET_ARN=${SecretArn}
              export ARTIFACT_BUCKET_NAME=${ArtifactBucket}
              export SQS_URL=${SqsUrlValue}
              export STATE_BUCKET=${StateBucketValue}
              export STATE_FILE_KEY=${StateFileValue}
              
              echo
              echo "Main setup script location      : s3://${ArtifactBucket}/cumulus-tunnel-setup.sh"
              echo "Secondary setup script location : s3://${ArtifactBucket}/additional-setup.sh"
              echo "SQS Url                         : $SQS_URL"
              echo "State File                      : s3://$STATE_BUCKET/$STATE_FILE_KEY"
              echo

              aws s3 cp s3://${ArtifactBucket}/cumulus-tunnel-setup.sh /tmp/cumulus-tunnel-setup.sh || true
              aws s3 cp s3://${ArtifactBucket}/additional-setup.sh /tmp/additional-setup.sh || true

              chmod 700 /tmp/cumulus-tunnel-setup.sh || true
              chmod 700 /tmp/additional-setup.sh || true

              /tmp/cumulus-tunnel-setup.sh || true
              /tmp/additional-setup.sh || true
              --==BOUNDARY==--
            - SecretArn: !ImportValue  CumulusTunnelAuthTokenSecretArn
              ArtifactBucket: !Ref ArtifactBucketNameParam
              SqsUrlValue: !Ref TunnelInstructionQueue
              StateBucketValue: !Ref CumulusTunnelBucketNameParam
              StateFileValue: !Ref StateFileKeyParam

# TODO - Create exports for all references 
# TODO - Create unique DNS records for the admin server.

  ########################################
  ###
  ### EC2 AUTOSCALING GROUP & ALB 4 HTTP
  ###
  ########################################

  CumulusTunnelInstanceAutoscalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties: 
      AutoScalingGroupName: !Sub '${AWS::StackName}-AutoScalingGroup'
      LaunchTemplate: 
        LaunchTemplateId: !Ref InstanceHostLaunchTemplate
        Version: !GetAtt InstanceHostLaunchTemplate.DefaultVersionNumber
      DesiredCapacity: '1'
      MinSize: '1'
      MaxSize: '1'
      VPCZoneIdentifier:
      - !Ref SubnetId1Param
      - !Ref SubnetId2Param
      - !Ref SubnetId3Param
      Tags:
      - Key: 'Name'
        Value: 'cumulus-tunnel'
        PropagateAtLaunch: true
      TargetGroupARNs:
      - !Ref CumulusTunnelHttpTargetGroup
      - !Ref CumulusTunnelAdminTargetGroup

  CumulusTunnelHttpTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: cumulus-tunnel-http
      TargetType: 'instance'
      IpAddressType: 'ipv4'
      Protocol: 'HTTP'
      Port: 80
      VpcId: !Ref VpcId1Param
      HealthCheckEnabled: True
      HealthCheckProtocol: 'HTTP'
      HealthCheckPort: 80
      HealthCheckPath: '/'
      HealthCheckIntervalSeconds: 300
      HealthCheckTimeoutSeconds: 120
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      UnhealthyThresholdCount: 3

  CumulusTunnelAdminTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: !Ref ManagementDomainRecordParam
      TargetType: 'instance'
      IpAddressType: 'ipv4'
      Protocol: 'HTTP'
      Port: 8081
      VpcId: !Ref VpcId1Param
      HealthCheckEnabled: True
      HealthCheckProtocol: 'HTTP'
      HealthCheckPort: 8081
      HealthCheckPath: '/'
      HealthCheckIntervalSeconds: 300
      HealthCheckTimeoutSeconds: 120
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      UnhealthyThresholdCount: 3

  CumulusTunnelAlb:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: !Ref ManagementDomainRecordParam
      Type: 'application'
      Scheme: 'internal'
      IpAddressType: 'ipv4'
      SecurityGroups:
      - !Ref TunnelInstanceAlbSecurityGroup
      Subnets:
      - !Ref SubnetId1Param
      - !Ref SubnetId2Param
      - !Ref SubnetId3Param
      LoadBalancerAttributes: 
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: true

  CumulusTunnelListener80:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      Protocol: 'HTTP'
      Port: 80
      LoadBalancerArn: !Ref CumulusTunnelAlb
      DefaultActions:
        - Type: 'redirect'
          RedirectConfig:
            Protocol: 'HTTPS'
            Port: 443
            Host: "#{host}"
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: "HTTP_301"

  CumulusTunnelListener443:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    DependsOn: 
    - CumulusTunnelHttpTargetGroup
    - CumulusTunnelInstanceAutoscalingGroup
    Properties:
      Protocol: 'HTTPS'
      Port: 443
      LoadBalancerArn: !Ref CumulusTunnelAlb
      SslPolicy: 'ELBSecurityPolicy-TLS-1-2-Ext-2018-06'
      Certificates:
      - CertificateArn: !Ref DomainCertificateArnParam
      DefaultActions:
      - Type: 'forward'
        ForwardConfig:
          TargetGroups:
          - TargetGroupArn: !Ref CumulusTunnelHttpTargetGroup
            Weight: 1

  CumulusTunnelListener8081:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    DependsOn: 
    - CumulusTunnelInstanceAutoscalingGroup
    - CumulusTunnelAdminTargetGroup
    Properties:
      Protocol: 'HTTPS'
      Port: 8081
      LoadBalancerArn: !Ref CumulusTunnelAlb
      SslPolicy: 'ELBSecurityPolicy-TLS-1-2-Ext-2018-06'
      Certificates:
      - CertificateArn: !Ref DomainCertificateArnParam
      DefaultActions:
      - Type: 'forward'
        ForwardConfig:
          TargetGroups:
          - TargetGroupArn: !Ref CumulusTunnelAdminTargetGroup
            Weight: 1

  CumulusTunnelDnsRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref DefaultRoute53ZoneIdParam
      Type: 'A'
      Name: !Sub '${ManagementDomainRecordParam}.${DefaultRoute53DomainParam}'
      AliasTarget:
        HostedZoneId: !GetAtt 'CumulusTunnelAlb.CanonicalHostedZoneID'
        DNSName: !GetAtt 'CumulusTunnelAlb.DNSName'


#######################################################################################################################
###
###     OUTPUTS
###
#######################################################################################################################

Outputs:

  CumulusTunnelInstanceAutoscalingGroupName:
    Value: !Ref CumulusTunnelInstanceAutoscalingGroup
    Export:
      Name: 'CumulusTunnelInstanceAutoscalingGroupName'
  
