---
AWSTemplateFormatVersion: '2010-09-09'

Description: "IaC for https://github.com/nicc777/home-tunnel-via-csp"

#######################################################################################################################
###
###     PARAMETERS
###
#######################################################################################################################

Parameters:

  Route53ZoneIdParam:
    Type: 'String'
    MinLength: 1
    Description: "The default Route 53 Zone ID for DNS records. Will also be used for the management UI record"

  Route53DomainParam:
    Type: 'String'
    MinLength: 1
    Description: "The default domain"

  DomainRecordValueParam:
    Type: 'String'
    MinLength: 1
    Description: "The default management sub-domain for the management UI"
    Default: "cumulus-tunnel-admin"

  RelayServerManagementDomain:
    Type: 'String'
    MinLength: 1


#######################################################################################################################
###
###     RESOURCES
###
#######################################################################################################################

Resources:

  RelayServerAdminDnsRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref Route53ZoneIdParam
      Type: 'A'
      Name: !Sub '${DomainRecordValueParam}.${Route53DomainParam}'
      AliasTarget:
        HostedZoneId: 
          Fn::ImportValue:
            !Sub '${RelayServerManagementDomain}-alb-zoneid'
        DNSName: 
          Fn::ImportValue:
            !Sub '${RelayServerManagementDomain}-alb-dnsname'


