---
AWSTemplateFormatVersion: '2010-09-09'

Description: "SQS queue to trigger Lambda Function"

#######################################################################################################################
###
###     PARAMETERS
###
#######################################################################################################################

Parameters:

  ArtifactBucketNameParam:
    Type: 'String'
    MinLength: 1

  LambdaFunctionS3KeyParam:
    Type: 'String'
    MinLength: 1
    Default: "handler_s3_object_created.zip"

  VpcId1Param:
    Type: 'String'
    MinLength: 1

  VpcCidrParam:
    Type: 'String'
    MinLength: 1

  SubnetId1Param:
    Type: 'String'
    MinLength: 1

  SubnetId2Param:
    Type: 'String'
    MinLength: 1

  SubnetId3Param:
    Type: 'String'
    MinLength: 1

  DebugParam:
    Type: 'String'
    Default: "0"
    Description: "To enable DEBUG logging for AWS Lambda function, set this value to 1"

  QueueNameParam:
    Type: 'String'
    MinLength: 1
    Description: "Unique name of the SQS Queue"

  PythonHandlerParam:
    Type: 'String'
    MinLength: 1
    Description: "The Python handler. Example value for the hello_world.py function: hello_world.handler"

  ApiCommandParam:
    Type: 'String'
    MinLength: 1
    Description: "The API command that will target this SQS and Lambda Function"


#######################################################################################################################
###
###     RESOURCES
###
#######################################################################################################################

Resources:

  ########################################
  ###
  ### SQS
  ###
  ########################################

  SqsQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      MaximumMessageSize: 102400
      MessageRetentionPeriod: 86400
      QueueName: !Ref QueueNameParam
      VisibilityTimeout: 300

  SqsQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    DependsOn:
    - CumulusTunnelLambdaFunction
    - SqsQueue
    Properties:
      Queues:
      - !Ref SqsQueue
      PolicyDocument:
        Version: 2012-10-17
        Id: AllowLambdaToReceiveMessages
        Statement:
        - Sid: !Sub '${AWS::StackName}-SqsQueuePolicy-sid-1'
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          - sqs:GetQueueAttributes
          Resource: !GetAtt SqsQueue.Arn
        # Important to allow sending messages from other sources as well.
        - Sid: !Sub '${AWS::StackName}-SqsQueuePolicy-sid-2' 
          Effect: Allow
          Principal:
            AWS: "*" # TODO restrict this to specific ARNs for better security
          Action: sqs:SendMessage
          Resource: !GetAtt SqsQueue.Arn

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CumulusTunnelLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt SqsQueue.Arn

  EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      FunctionName: !GetAtt CumulusTunnelLambdaFunction.Arn
      EventSourceArn: !GetAtt SqsQueue.Arn
      BatchSize: 1 # Number of messages to process in each Lambda invocation
      Enabled: true
      # MaximumBatchingWindowInSeconds: 60 # Optional: maximum time to wait to accumulate BatchSize messages
      # MaximumRetryAttempts: 3 # Optional: Maximum number of retries per batch
      # StartingPosition: Latest # Optional: Where to start reading messages (Latest or TrimHorizon)
      # ReportBatchItemFailures: true # Optional: Enable partial batch responses to handle failures in a batch
      # TumblingWindowInSeconds: 60 # Optional: Time window (in seconds) for collecting messages before invoking the function.

  

  ########################################
  ###
  ### LAMBDA - BASE 
  ###
  ########################################

  CumulusTunnelLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole # Basic Lambda permissions
      - arn:aws:iam::aws:policy/AmazonSQSFullAccess # Needed to interact with SQS (could be more restrictive)
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: !Sub '${AWS::StackName}-policy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          # logging
          - Effect: Allow
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            Resource: arn:aws:logs:*:*:*
          # networkinterface
          - Effect: Allow
            Action:
            - "ec2:DescribeNetworkinterfaces"
            - "ec2:DeleteNetworkinterface"
            - "ec2:Describe*"
            - "ec2:DescribeVpcs"
            - "ec2:DescribeSubnets"
            - "ec2:CreateNetworkinterface"
            Resource: "*"
          # sqs
          - Effect: Allow
            Action:
            - "sqs:SendMessage"
            - "sqs:GetQueueUrl"
            Resource: "*"
          # CloudFormation
          - Effect: Allow
            Action:
            - "cloudformation:CancelUpdateStack"
            - "cloudformation:DescribeStackResources"
            - "cloudformation:UpdateStackSet"
            - "cloudformation:CreateChangeSet"
            - "cloudformation:DeleteStackSet"
            - "cloudformation:DeleteChangeSet"
            - "cloudformation:DescribeStacks"
            - "cloudformation:DescribeStackEvents"
            - "cloudformation:DescribeStackSet"
            - "cloudformation:CreateStack"
            - "cloudformation:GetTemplate"
            - "cloudformation:DeleteStack"
            - "cloudformation:DescribeChangeSet"
            - "cloudformation:ExecuteChangeSet"
            - "cloudformation:ListChangeSets"
            - "cloudformation:ListStackResources"
            - "cloudformation:ListStacks"
            Resource: 
            - !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stack/*/*"
            - !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:type/resource/*"
            - !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stackset-target/*"
            - !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stackset/*:*"
          # S3
          - Effect: 'Allow'
            Action: 
            - 's3:HeadObject'
            - 's3:GetObject'
            - 's3:ListObjectsV2'
            - 's3:CopyObject'
            Resource: 
              Fn::Sub: 
              - 'arn:aws:s3:::${Bucket}/*'
              - Bucket: !Ref ArtifactBucketNameParam
          # EC2 full access
          - Action: ec2:*
            Effect: Allow
            Resource: "*"
          - Effect: Allow
            Action: elasticloadbalancing:*
            Resource: "*"
          - Effect: Allow
            Action: cloudwatch:*
            Resource: "*"
          - Effect: Allow
            Action: autoscaling:*
            Resource: "*"
          - Effect: Allow
            Action: iam:CreateServiceLinkedRole
            Resource: "*"
            Condition:
              StringEquals:
                iam:AWSServiceName:
                - autoscaling.amazonaws.com
                - ec2scheduled.amazonaws.com
                - elasticloadbalancing.amazonaws.com
                - spot.amazonaws.com
                - spotfleet.amazonaws.com
          # Route 53
          - Effect: Allow
            Action:
            - route53:GetHostedZone
            - route53:ChangeResourceRecordSets
            - route53:GetHostedZoneLimit
            - route53:ListHostedZones
            Resource: "*"
          # IAM
          - Effect: Allow
            Action:
            - iam:CreateInstanceProfile
            - iam:GetPolicyVersion
            - iam:ListRoleTags
            - iam:DeleteGroup
            - iam:UpdateGroup
            - iam:DeletePolicy
            - iam:CreateRole
            - iam:AttachRolePolicy
            - iam:PutRolePolicy
            - iam:GetGroup
            - iam:AddRoleToInstanceProfile
            - iam:DetachRolePolicy
            - iam:DeleteRolePolicy
            - iam:DetachGroupPolicy
            - iam:ListAttachedGroupPolicies
            - iam:ListPolicyTags
            - iam:ListRolePolicies
            - iam:CreatePolicyVersion
            - iam:PutGroupPolicy
            - iam:ListPolicies
            - iam:DeleteInstanceProfile
            - iam:GetRole
            - iam:CreateGroup
            - iam:GetInstanceProfile
            - iam:GetPolicy
            - iam:ListRoles
            - iam:UpdateRoleDescription
            - iam:ListUserPolicies
            - iam:ListInstanceProfiles
            - iam:CreatePolicy
            - iam:ListPolicyVersions
            - iam:ListUsers
            - iam:UpdateRole
            - iam:ListGroups
            - iam:GetGroupPolicy
            - iam:DeleteGroupPolicy
            - iam:GetRolePolicy
            - iam:DeletePolicyVersion
            - iam:PassRole
            Resource: "*"


  ########################################
  ###
  ### LAMBDA FUNCTION :: OBJECT CREATED
  ###
  ########################################

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: CumulusTunnelLambdaFunction
    Properties:
      LogGroupName: 
        Fn::Join:
        - ''
        - - "/aws/lambda/"
          - Ref: CumulusTunnelLambdaFunction
      RetentionInDays: 7

  CumulusTunnelLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'cumulus-tunnel-${ApiCommandParam}'
      Code:
        S3Bucket: !Ref ArtifactBucketNameParam
        S3Key: !Ref LambdaFunctionS3KeyParam
      Description: "Lambda function for Cumulus Tunnel Command Processing"
      Handler: !Ref PythonHandlerParam
      MemorySize: 128
      PackageType: Zip
      Role: !GetAtt CumulusTunnelLambdaRole.Arn
      Environment:
        Variables:
          DEBUG: !Ref DebugParam
          ARTIFACT_BUCKET: !Ref ArtifactBucketNameParam
          COMMAND_QUEUE_URL: !Ref SqsQueue
          VPC_ID: !Ref VpcId1Param
          VPC_CIDR: !Ref VpcCidrParam
          SUBNET_1_ID: !Ref SubnetId1Param
          SUBNET_2_ID: !Ref SubnetId2Param
          SUBNET_3_ID: !Ref SubnetId3Param
      Runtime: python3.12
      Timeout: 300


#######################################################################################################################
###
###     OUTPUTS
###
#######################################################################################################################

Outputs:

  SqsQueueUrl:
    Value: !Ref SqsQueue
    Export:
      Name: !Sub '${AWS::StackName}-SqsQueueUrl'

  CumulusTunnelLambdaFunctionName:
    Value: !Ref CumulusTunnelLambdaFunction
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionName'

  SqsAndLambdaStackName:
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub 'SqsAndLambdaStackName-${AWS::StackName}'

  PythonName:
    Value: !Ref PythonHandlerParam
    Export:
      Name: !Sub '${AWS::StackName}-PythonName'

  ApiCommandName:
    Value: !Ref ApiCommandParam
    Export:
      Name: !Sub '${AWS::StackName}-ApiCommandParam'


  
